### ISSUE TITLE
Cleanup issues when killing subprocess

### ISSUE THREAD

**Issue by jmaroeder** [Peilonrayz/teetime#1]
I have code roughly equivalent to the following running as part of some unit tests:
```python
import io
import sys
import time

import teetime


my_out = io.StringIO()
sinks = teetime.Sinks((sys.stdout, my_out), ())
print(my_out)
process = sinks.popen(["sh", "-c", "echo sleeping; sleep 5; echo done"], text=True)
threads = sinks.make_threads(process)
time.sleep(1)
print("killing")
process.kill()
process.wait()
```

When I try running this as a standalone file, it runs fine and I have no issues. However, when I run them as part of a test (triggered by `pytest`), I receive errors that look like the following:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-11:
Exception in thread Thread-5Traceback (most recent call last):
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Exception in thread Thread-12Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Exception in thread Exception in thread   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Thread-15:
Thread-3    self.run()Exception in thread Thread-14:
Traceback (most recent call last):
    :
```

I've tried overriding `threading.excepthook` to inspect these further (since the traceback/exception appear to be smushed), and they seem to be caused by an attempt to write to a closed file. I'm guessing this might have something to do with the way that pytest captures sys.stdout.

I guess what I'm wondering if if you have any insight how to prevent these exceptions from piling up. Note that they don't actually cause tests to fail (as they shouldn't), they're just cluttering up the output.

**Comment by Peilonrayz** [comment]
Hey, thank you for reporting this. I've tried to reproduce this, however these errors aren't appearing for me. What Python version and OS are you running?

Additionally please could you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).  
Here is an example of me not getting the errors:

```fish
               $ mkdir example
               $ cd example
       example $ python -m virtualenv venv
       example $ . venv/bin/activate.fish
(venv) example $ pip install pytest teetime
Successfully installed attrs-20.2.0 iniconfig-1.0.1 more-itertools-8.5.0 packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 pytest-6.0.1 six-1.15.0 toml-0.10.1
(venv) example $ vim test_example.py
(venv) example $ pytest -v
=========================================== test session starts ===========================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- [redacted]/example/venv/bin/python
cachedir: .pytest_cache
rootdir: [redacted]/example
collected 1 item                                                                                          

test_example.py::test_example PASSED                                                                [100%]

============================================ 1 passed in 1.01s ============================================
```

`test_example.py`

```python
import io
import sys
import time

import teetime


def test_example():
    my_out = io.StringIO()
    sinks = teetime.Sinks((sys.stdout, my_out), ())
    print(my_out)
    process = sinks.popen(["sh", "-c", "echo sleeping; sleep 5; echo done"], text=True)
    threads = sinks.make_threads(process)
    time.sleep(1)
    print("killing")
    process.kill()
    process.wait()
```

**Comment by jmaroeder** [comment]
Thanks for such a quick response!

My initial example _also_ did not produce errors for me after I actually tried it - I believe it may be related to the lack of output that was being generated when the process was killed. I've made a smaller example below that reproduces the error in multiple environments.

On my local machine (macOS 10.15.6, python 3.8.5):

```console
$ mkdir teetime-1
$ cd teetime-1
$ python3.8 -m venv venv
$ . venv/bin/activate.fish
$ pip install pytest teetime
$ vim test_example.py
$ pytest

================================================= test session starts ==================================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/james-roeder/src/scratch/teetime-1
collected 1 item

test_example.py .                                                                                                [100%]

================================================== 1 passed in 0.02s ===================================================
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```
`test_example.py`:
```python
import io
import sys
import time

import teetime


def test_example():
    my_out = io.StringIO()
    sinks = teetime.Sinks((sys.stdout, my_out), ())
    process = sinks.popen(["python", "-c", "while True: print('.')"], text=True)
    threads = sinks.make_threads(process)
    process.kill()
```

I get similar output when I run it through a simple Alpine-based Docker image:

```console
$ docker run --rm -it --entrypoint sh python:3.8-alpine
/ # mkdir test
/ # cd test
/test # pip install pytest teetime
/test # vi test_example.py
/test # pytest
================================================= test session starts ==================================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /test
collected 1 item

test_example.py .                                                                                                [100%]

================================================== 1 passed in 0.01s ===================================================
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
```

**Comment by Peilonrayz** [comment]
Thanks for the update, I have reproduced this.

Unfortunately I am not very skilled with debugging threads and I am rather busy at the moment. I should be able to look into debugging this in a weeks time.

**Comment by jmaroeder** [comment]
Well, this gave me an excuse to learn some rather kludgy thread debugging.

`test_example.py`
```python
import io
import sys
import threading
import time
import traceback
from types import TracebackType

import teetime


def my_excepthook(args):
    print(f"threading exception ({args}")
    tb: TracebackType = args.exc_traceback
    while tb:
        print(f"tb: {tb}")
        frame = tb.tb_frame
        while frame:
            print(f"{frame.f_code.co_filename}:{frame.f_lineno}")
            frame = frame.f_back
        tb = tb.tb_next
    print("...")


threading.excepthook = my_excepthook


def test_example():
    my_out = io.StringIO()
    sinks = teetime.Sinks((sys.stdout, my_out), ())
    process = sinks.popen(["python", "-c", "while True: print('.')"], text=True)
    threads = sinks.make_threads(process)
    process.kill()
```

Using the above code, I was able to narrow down the problem to a `ValueError('I/O operation on closed file.')`. I realized that the thread(s) continued to run after the file was closed. It did not appear that calls to `close_threads` would stop them from attempting to write to the target sinks.

I've got a PR incoming that adds another option to the `as_callbacks` method to silently suppress `ValueError` when writing, but I can certainly understand if you'd like to approach it another way!

**Comment by jmaroeder** [comment]
@Peilonrayz just wondering if you ever got a chance to take a look at PR #2, or if you had thoughts about another way to approach this
